config:
  target: 'http://localhost:3000'
  phases:
    - duration: 60
      arrivalRate: 5
scenarios:
  - flow:
      - post:
          url: '/api/todos'
          json:
            title: 'Load Test Todo'
      - get:
          url: '/api/todos'